import { Router, Request, Response } from 'express';
import jwt from 'jsonwebtoken';
import { randomUUID } from 'crypto';
import { config } from '../../config/environment';
import { verifyToken } from '../../utils/jwt';
import { authService } from '../../services/auth/auth.service';
import logger from '../../utils/logger';

// ─── Environment-Aware Discovery Base URL ──────────────────────────────────────
const BASE_URL = config.nodeEnv === 'development'
  ? 'http://localhost:4001'
  : config.apiUrl; // e.g. https://api.evidentlyaeo.com

export const wellKnownRouter = Router();

/**
 * GET /.well-known/oauth-authorization-server
 * RFC 8414 OAuth 2.0 Authorization Server Metadata
 */
wellKnownRouter.get('/.well-known/oauth-authorization-server', (req: Request, res: Response) => {
  res.json({
    issuer: BASE_URL,
    authorization_endpoint: `${config.frontendUrl}/mcp/consent`, // Offloaded to frontend
    token_endpoint: `${BASE_URL}/oauth/token`,
    response_types_supported: ['code'],
    grant_types_supported: ['authorization_code', 'refresh_token'],
    token_endpoint_auth_methods_supported: ['client_secret_post', 'none'], // Allow PKCE
    code_challenge_methods_supported: ['S256'],
    scopes_supported: ['read:dashboard', 'read:queries', 'read:citations', 'read:recommendations', 'read:domain', 'read:brands'],
    registration_endpoint: `${BASE_URL}/oauth/register`,
  });
});

/**
 * GET /.well-known/openid-configuration
 * RFC 8414 — Compatibility shim for OIDC-aware discovery clients
 */
wellKnownRouter.get('/.well-known/openid-configuration', (req: Request, res: Response) => {
  res.json({
    issuer: BASE_URL,
    authorization_endpoint: `${config.frontendUrl}/mcp/consent`,
    token_endpoint: `${BASE_URL}/oauth/token`,
    registration_endpoint: `${BASE_URL}/oauth/register`,
    response_types_supported: ['code'],
    grant_types_supported: ['authorization_code', 'refresh_token'],
    code_challenge_methods_supported: ['S256'],
  });
});

/**
 * GET /.well-known/oauth-protected-resource
 * RFC 9728 — tells clients where the authorization server lives
 */
wellKnownRouter.get('/.well-known/oauth-protected-resource', (req: Request, res: Response) => {
  res.json({
    resource: BASE_URL,
    authorization_servers: [BASE_URL],
  });
});

// Also handle the path-suffixed variant Inspector tries first
wellKnownRouter.get('/.well-known/oauth-protected-resource/mcp', (req: Request, res: Response) => {
  res.json({
    resource: `${BASE_URL}/mcp`,
    authorization_servers: [BASE_URL],
  });
});


export const oauthRouter = Router();

/**
 * POST /oauth/register
 * RFC 7591 Dynamic Client Registration
 * Inspector requires this to self-register before initiating OAuth flow
 */
oauthRouter.post('/register', (req: Request, res: Response) => {
  const { client_name, redirect_uris } = req.body;

  // Return a unique client_id per registration
  res.status(201).json({
    client_id: randomUUID(),
    client_name: client_name || 'MCP Client',
    redirect_uris: redirect_uris || [],
    grant_types: ['authorization_code', 'refresh_token'],
    response_types: ['code'],
    token_endpoint_auth_method: 'none',
  });
});

/**
 * POST /token
 * Adapter endpoint the frontend/client calls to exchange a Supabase Session or Authorization Code
 * for an MCP-specific access token.
 */
oauthRouter.post('/token', async (req: Request, res: Response): Promise<void> => {
  try {
    const { grant_type, code, refresh_token, scopes } = req.body;
    const secret = process.env.SUPABASE_JWT_SECRET || config.jwt.secret;

    if (!secret) {
      res.status(500).json({ error: 'Server misconfiguration: missing JWT secret' });
      return;
    }

    if (grant_type === 'authorization_code') {
      // In this thin-adapter architecture, "code" passed from the frontend is actually the short-lived 
      // Supabase JWT the user generated by logging in successfully on the Consent UI. 

      if (!code) {
        res.status(400).json({ error: 'invalid_request', error_description: 'Missing code parameter' });
        return;
      }

      // Verify the user via their real Supabase session
      let payload;
      try {
        payload = verifyToken(code);
      } catch (err) {
        res.status(401).json({ error: 'invalid_grant', error_description: 'Invalid or expired authorization code/token' });
        return;
      }

      const user = await authService.getUserProfile(payload.sub as string);
      if (!user) {
        res.status(401).json({ error: 'invalid_grant', error_description: 'User not found' });
        return;
      }

      logger.debug('[OAuth] Token minted', { userId: user.id });

      // Mint the MCP Access Token
      const mcpAccessToken = jwt.sign(
        {
          sub: user.id,
          customer_id: user.customer_id,
          aud: 'evidentlyaeo-mcp', // Strict custom audience
          scopes: Array.isArray(scopes) ? scopes : (scopes ? scopes.split(' ') : ['read:dashboard', 'read:brands']),
        },
        secret,
        { expiresIn: '15m' } // Short lived
      );

      // Refresh token for the MCP client.
      const mcpRefreshToken = jwt.sign(
        { sub: user.id, customer_id: user.customer_id, type: 'mcp_refresh' },
        secret,
        { expiresIn: '30d' }
      );

      res.json({
        access_token: mcpAccessToken,
        token_type: 'Bearer',
        expires_in: 900, // 15 mins in seconds
        refresh_token: mcpRefreshToken,
      });
      return;
    }

    if (grant_type === 'refresh_token') {
      if (!refresh_token) {
        res.status(400).json({ error: 'invalid_request', error_description: 'Missing refresh_token parameter' });
        return;
      }

      let refreshPayload;
      try {
        refreshPayload = jwt.verify(refresh_token, secret) as any;
        if (refreshPayload.type !== 'mcp_refresh') throw new Error();
      } catch (err) {
        res.status(401).json({ error: 'invalid_grant', error_description: 'Invalid or expired refresh token' });
        return;
      }

      // Re-mint MCP tokens
      const mcpAccessToken = jwt.sign(
        { sub: refreshPayload.sub, customer_id: refreshPayload.customer_id, aud: 'evidentlyaeo-mcp', scopes: ['read:dashboard', 'read:brands'] },
        secret,
        { expiresIn: '15m' }
      );
      
      const newMcpRefreshToken = jwt.sign(
        { sub: refreshPayload.sub, customer_id: refreshPayload.customer_id, type: 'mcp_refresh' },
        secret,
        { expiresIn: '30d' }
      );

      res.json({
        access_token: mcpAccessToken,
        token_type: 'Bearer',
        expires_in: 900,
        refresh_token: newMcpRefreshToken,
      });
      return;
    }

    res.status(400).json({ error: 'unsupported_grant_type' });
  } catch (error) {
    console.error('[OAuth Adapter error]', error);
    res.status(500).json({ error: 'server_error' });
  }
});
